from typing import Dict, final

from . import _tracing_subscriber as _tracing_subscriber

def example_function() -> Dict[str, str]: ...
async def example_function_async() -> Dict[str, str]: ...
@final
class ExampleStruct:
    def __new__(cls) -> "ExampleStruct": ...
    def example_method(self) -> Dict[str, str]: ...
    async def example_method_async(self) -> Dict[str, str]: ...
