[packages.rigetti-pyo3]
versioned_files = [
    "crates/rigetti-pyo3/Cargo.toml",
    "Cargo.lock",
    { path = "Cargo.toml", dependency = "rigetti-pyo3" },
    { path = "Cargo.lock", dependency = "rigetti-pyo3" },
]
changelog = "crates/rigetti-pyo3/CHANGELOG.md"
# Includes scopes of workspace dependencies: optipy
scopes = ["rigetti-pyo3", "optipy"]

[packages.optipy]
versioned_files = [
    "crates/optipy/Cargo.toml",
    "Cargo.lock",
    { path = "Cargo.toml", dependency = "optipy" },
    { path = "Cargo.lock", dependency = "optipy" },
]
changelog = "crates/optipy/CHANGELOG.md"
scopes = ["optipy"]

[packages.opentelemetry]
versioned_files = [
    "crates/opentelemetry/Cargo.toml",
    "Cargo.lock",
    { path = "Cargo.toml", dependency = "pyo3-opentelemetry" },
    { path = "Cargo.lock", dependency = "pyo3-opentelemetry" },
]
changelog = "crates/opentelemetry/CHANGELOG.md"
# Includes scopes of workspace dependencies: opentelemetry-macros
scopes = [
    "opentelemetry",
    "pyo3-opentelemetry",
    "opentelemetry-macros",
    "pyo3-opentelemetry-macros",
]

[packages.opentelemetry-macros]
versioned_files = [
    "crates/opentelemetry-macros/Cargo.toml",
    "Cargo.lock",
    { path = "Cargo.toml", dependency = "pyo3-opentelemetry-macros" },
    { path = "Cargo.lock", dependency = "pyo3-opentelemetry-macros" },
]
changelog = "crates/opentelemetry-macros/CHANGELOG.md"
scopes = ["opentelemetry-macros", "pyo3-opentelemetry-macros"]

[packages.tracing-subscriber]
# Includes `tracing-subscriber-build`.
versioned_files = [
    "crates/tracing-subscriber/Cargo.toml",
    "crates/tracing-subscriber-build/Cargo.toml",
    "Cargo.lock",
    { path = "Cargo.toml", dependency = "pyo3-tracing-subscriber" },
    { path = "Cargo.toml", dependency = "pyo3-tracing-subscriber-build" },
    { path = "Cargo.lock", dependency = "pyo3-tracing-subscriber" },
    { path = "Cargo.lock", dependency = "pyo3-tracing-subscriber-build" },
]
changelog = "crates/tracing-subscriber/CHANGELOG.md"
# Includes scopes of workspace dependencies: rigetti-pyo3 (and its dependency optipy)
scopes = [
    "tracing-subscriber",
    "pyo3-tracing-subscriber",
    "rigetti-pyo3",
    "optipy",
]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release [skip ci]\""

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[github]
owner = "rigetti"
repo = "rigetti-pyo3"
