[env]
    CARGO_HACK_COMMON_FLAGS = "--feature-powerset --optional-deps --exclude-features extension-module"

[tasks.clean]
    clear = true
    script = """
    rm -f *.profraw
    cargo clean
    """

[tasks.install-coverage-tools]
    install_crate = { rustup_component_name = "llvm-tools-preview" }

[tasks.install-cargo-hack]
    install_crate = { crate_name = "cargo-hack", binary = "cargo-hack", test_arg = ["hack", "--help"] }

[tasks.check]
    clear = true
    dependencies = ["install-cargo-hack"]
    script = "cargo hack check $CARGO_HACK_COMMON_FLAGS --all-targets"

[tasks.clippy]
    clear = true
    dependencies = ["install-clippy-any", "install-cargo-hack"]
    script = "cargo hack clippy $CARGO_HACK_COMMON_FLAGS --all-targets"

[tasks.deadlinks]
    install_crate = "cargo-deadlinks"
    command = "cargo"
    args = ["deadlinks", "--check-http", "--check-intra-doc-links"]

[tasks.deny]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "all"]

[tasks.deny-advisories]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "advisories"]

[tasks.deny-ban]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "ban"]

[tasks.deny-bans]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "bans"]

[tasks.deny-license]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "license"]

[tasks.deny-licenses]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "licenses"]

[tasks.deny-sources]
    install_crate = "cargo-deny"
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKING_DIRECTORY}/deny.toml", "sources"]

[tasks.geiger]
    install_crate = "cargo-geiger"
    command = "cargo"
    args = ["geiger"]

[tasks.license]
    install_crate = "cargo-license"
    command = "cargo"
    args = ["license", "--all-features", "--avoid-dev-deps"]

[tasks.msrv]
    install_crate = "cargo-msrv"
    command = "cargo"
    args = ["msrv"]

[tasks.msrv-verify]
    install_crate = "cargo-msrv"
    command = "cargo"
    args = ["msrv", "verify"]

[tasks.outdated]
    install_crate = "cargo-outdated"
    command = "cargo"
    args = ["outdated"]

[tasks.check-all]
    dependencies = ["deny", "check", "clippy", "deadlinks", "outdated", "msrv-verify"]
