# *****************************************************************************
# *                             AUTO-GENERATED CODE                           *
# *                                                                           *
# * This code was generated by the `pyo3-tracing-subscriber` crate. Any       *
# * modifications to this file should be made to the script or the generation *
# * process that produced this code. Specifically, see:                       *
# * `pyo3_tracing_subscriber_build::write_stub_files`                        *
# *                                                                           *
# * Do not manually edit this file, as your changes may be overwritten the    *
# * next time the code is generated.                                          *
# *****************************************************************************

from __future__ import annotations
from typing import TYPE_CHECKING

from . import file as file
{{#if layer_otel_otlp_file }}from . import otel_otlp_file as otel_otlp_file{{/if}}
{{#if layer_otel_otlp}}from . import otel_otlp as otel_otlp{{/if}}

if TYPE_CHECKING:
  {{#if any_additional_layer}}from typing import Union{{/if}}

  {{#if any_additional_layer}}Config = Union[
    file.Config,
    {{#if layer_otel_otlp_file }}otel_otlp_file.Config,{{/if}}
    {{#if layer_otel_otlp }}otel_otlp.Config,{{/if}}
      ]{{else}}Config = file.Config{{/if}}
  """
  One of the supported layer configurations that may be set on the subscriber configuration.
  """
