//! The `init_submodule` generated by `create_init_submodule!` must be `pub`: a dependent crate
//! registers this module's classes into its own module tree by passing the function to its own
//! `create_init_submodule!`, which is how a foreign extension module's types get re-exported
//! under a local name.

use rigetti_pyo3::pyo3::{types::PyModule, Bound, PyResult, Python};

type InitSubmodule = fn(&str, Python<'_>, &Bound<'_, PyModule>) -> PyResult<()>;

mod submodule {
    rigetti_pyo3::create_init_submodule! {
        /// Doc comments still apply to the generated function.
    }
}

#[test]
fn generated_init_submodule_is_a_public_item() {
    let _: InitSubmodule = submodule::init_submodule;
}
